In [3]:
import torch
import torch.nn as nn

In [12]:
class my_model(nn.Module):
    def __init__(self):
        super(my_model, self).__init__()
        self.conv = nn.Conv2d(1, 1, 3, 1, 1)
        self.tensor = torch.randn(size=(1, 1, 5, 5))
        self.tensor2 = torch.randn(size=(1, 1))
        # self.register_buffer('my_buffer', self.tensor)
        self.register_buffer('my_buffer2', self.tensor2)

    def forward(self, x):
        return self.conv(x) + self.my_buffer2

In [13]:
x = torch.randn(size=(1, 1, 5, 5))
x = x.to('cuda')
model = my_model().cuda()
model(x)

tensor([[[[ 0.6497,  1.3396,  0.7057,  0.1417,  0.5024],
          [ 0.4814, -1.0371,  0.0776,  1.0947, -0.0881],
          [ 1.0307,  1.4001,  0.3567,  0.4859,  1.4404],
          [ 0.1567, -0.0184,  1.0105,  0.7972,  0.1046],
          [ 1.2096,  0.0359,  0.9822,  0.9014, -0.0739]]]], device='cuda:0',
       grad_fn=<AddBackward0>)

In [14]:
for para in model.parameters():
    print(para)

Parameter containing:
tensor([[[[ 0.2236, -0.2558, -0.1165],
          [ 0.0659,  0.2993,  0.2647],
          [-0.1937, -0.2561, -0.1188]]]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.1212], device='cuda:0', requires_grad=True)


In [15]:
print('.............................................................')
for buff in model.buffers():
    print(buff)

.............................................................
tensor([[0.7092]], device='cuda:0')


In [16]:
model.state_dict()

OrderedDict([('my_buffer2', tensor([[0.7092]], device='cuda:0')),
             ('conv.weight',
              tensor([[[[ 0.2236, -0.2558, -0.1165],
                        [ 0.0659,  0.2993,  0.2647],
                        [-0.1937, -0.2561, -0.1188]]]], device='cuda:0')),
             ('conv.bias', tensor([-0.1212], device='cuda:0'))])

In [ ]:
# Parameter containing:
# tensor([[[[ 0.1019,  0.3182,  0.1563],
#           [-0.0207, -0.0562,  0.1807],
#           [ 0.2703, -0.1186, -0.2867]]]], device='cuda:0', requires_grad=True)
# Parameter containing:
# tensor([-0.0992], device='cuda:0', requires_grad=True)
# .............................................................
# tensor([[[[ 1.3138,  1.3372,  1.6745, -0.8393, -0.1983],
#           [-1.3365,  1.0321, -0.7752,  1.4250,  0.9376],
#           [-0.9306,  0.1586,  0.5963, -1.0124, -0.6470],
#           [ 0.6429, -1.1386,  0.8107, -0.8500,  0.4866],
#           [ 0.0342,  1.5359,  0.6636,  0.2488,  0.0490]]]], device='cuda:0')
# tensor([[0.7401]], device='cuda:0')