In [3]:
import numpy as np
import torch

In [2]:
torch.__version__

'2.0.0+cu117'

In [6]:
a = torch.arange(12).reshape(3,4)
b = a.clone()
c = a.clone().reshape(4,3)

## torch.mul
point-wise 

In [5]:
o_mul = torch.mul(a, b)
print(o_mul.shape)
o_mul

torch.Size([3, 4])


tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]])

## torch.mm

matrix mul

In [7]:
o_mm = torch.mm(a, c)
print(o_mm.shape)
o_mm

torch.Size([3, 3])


tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262]])

## torch.bmm
batch matrix product
bmm(A, B)
A and B must be 3D which have same dim0 

$O_i = A_i \times B_i$

In [8]:
o_bmm = torch.bmm(a.reshape(2,3,2), b.reshape(2, 2, 3))
print(o_bmm.shape)
o_bmm

torch.Size([2, 3, 3])


tensor([[[  3,   4,   5],
         [  9,  14,  19],
         [ 15,  24,  33]],

        [[ 99, 112, 125],
         [129, 146, 163],
         [159, 180, 201]]])