In [1]:
%matplotlib inline


什么是Pytorch
================

这是一个基于Python的科学计算软件包，面向两组受众：

-  替代NumPy以使用GPU的功能
-  深度学习研究平台，可提供最大的灵活性和速度

开始吧
---------------

## 张量(Tensors)

张量与NumPy的ndarrays类似，此外，  
张量也可以在GPU上使用以加速计算。



In [2]:
from __future__ import print_function
import torch

创建一个未初始化的5x3矩阵：



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[-1.8736e-02,  5.3810e-43, -1.8736e-02],
        [ 5.3810e-43, -1.8736e-02,  5.3810e-43],
        [-1.8736e-02,  5.3810e-43, -1.8736e-02],
        [ 5.3810e-43, -1.8736e-02,  5.3810e-43],
        [-1.8736e-02,  5.3810e-43, -1.8736e-02]])


创建一个随机初始化的矩阵：



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1884, 0.9676, 0.0932],
        [0.0237, 0.8706, 0.1165],
        [0.8923, 0.6846, 0.2428],
        [0.1050, 0.1057, 0.4467],
        [0.2271, 0.8529, 0.5744]])


构造一个填充零且dtype long的矩阵：



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接从数据创建张量：



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


或基于现有张量创建张量。 这些方法将重复使用输入张量的属性，例如dtype，除非用户提供新值



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6246, -0.3308,  1.0961],
        [-0.2643, -1.9371, -0.7324],
        [-1.0433,  1.8659, -0.2630],
        [-0.5869, -0.8914,  1.2099],
        [-0.7889,  0.0762,  0.3997]])


打印它的大小：



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>注</h4><p>

``torch.Size`` 实际上是一个tuple，因此它支持所有tuple操作。</p></div>

## 运算(Operations)

运算有多种语法实现。在下面的示例中，我们将看一下加法运算。

加法：语法1



In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.5411, -0.2331,  1.4236],
        [ 0.4124, -1.0028, -0.6942],
        [-0.5186,  2.3691,  0.6042],
        [-0.3107, -0.7324,  1.7120],
        [-0.5278,  0.2224,  1.1851]])


加法：语法2



In [10]:
print(torch.add(x, y))

tensor([[-0.5411, -0.2331,  1.4236],
        [ 0.4124, -1.0028, -0.6942],
        [-0.5186,  2.3691,  0.6042],
        [-0.3107, -0.7324,  1.7120],
        [-0.5278,  0.2224,  1.1851]])


加法：提供输出张量作为参数(argument)



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.5411, -0.2331,  1.4236],
        [ 0.4124, -1.0028, -0.6942],
        [-0.5186,  2.3691,  0.6042],
        [-0.3107, -0.7324,  1.7120],
        [-0.5278,  0.2224,  1.1851]])


加法：就地(in-place)



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.5411, -0.2331,  1.4236],
        [ 0.4124, -1.0028, -0.6942],
        [-0.5186,  2.3691,  0.6042],
        [-0.3107, -0.7324,  1.7120],
        [-0.5278,  0.2224,  1.1851]])


<div class="alert alert-info"><h4>注</h4><p>

任何使张量就地发生变化的操作都将使用 ``_``.
    如: ``x.copy_(y)``, ``x.t_()``, 会改变 ``x``.</p></div>

您可以使用类似NumPy的标准索引来变出各种花样！



In [13]:
print(x[:, 1])

tensor([-0.3308, -1.9371,  1.8659, -0.8914,  0.0762])


调整大小：如果要调整张量的大小/形状，可以使用 ``torch.view``:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果您具有一个元素张量，请使用``.item()``获取该值作为Python数字。



In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5033])
0.5032538771629333


**稍后阅读:**

  [这里](https://pytorch.org/docs/torch)
  
包含了100多个Tensor运算，包括转置(transposing)、索引(indexing)、分割(slicing)、数学运算(mathematical operations)、线性代数(linear algebra)、随机数(random numbers)等。

NumPy转换
------------

将Torch张量转换为NumPy数组，反之亦然，这十分简单。

Torch张量和NumPy数组将共享其基础内存位置，并且更改一个将更改另一个。

## 将Torch张量转换为NumPy数组



In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


看看numpy数组的值如何变化。



In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## 将NumPy数组转换为Torch张量

查看更改numpy数组如何自动更改Torch Tensor



In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


除CharTensor之外，CPU上的所有张量都支持转换为NumPy并转回。

CUDA张量
------------

张量可以使用``.to``方法移动到任何设备上。


In [20]:
# 让我们仅在CUDA可用时运行此单元格
# 我们将使用``torch.device``对象将张量移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA设备对象
    y = torch.ones_like(x, device=device)  # 在GPU上直接创建张量
    x = x.to(device)                       # 或只使用字符串``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也可以一起改变dtype！

tensor([1.5033], device='cuda:0')
tensor([1.5033], dtype=torch.float64)


## Tensor 数据类型的转换

In [1]:
import torch 

In [2]:
a = torch.rand((4,3,5,5))
a.dtype

torch.float32

In [3]:
b = torch.tensor([1,2,3])
b.dtype

torch.int64

In [5]:
c = 3*b.type(torch.float32)
c.dtype

torch.float32

In [7]:
tensor = torch.tensor

In [9]:
total = [tensor([ 873.,  873.,  873., 6498., 6498., 6498., 6498., 6498., 6498., 6498.,
         333.,  333.,  333.,  333.,  333.,  762.], device='cuda:0'), tensor([ 762.,  762.,  762., 1986., 1986., 1296., 1296., 1296.,
1296., 1296.,
        1248., 1248., 1248., 1074., 1074., 1074.], device='cuda:0'), tensor([1074., 1074., 2481., 2481., 2481., 2586., 2586., 2586.,
2586., 2586.,
        2586., 1959., 1959., 1959., 1959., 1959.], device='cuda:0'), tensor([1959.,  741.,  741.,  741., 3786., 3786., 3786., 3786.,
3786., 3786.,
        3786., 3786., 3786., 3786., 3786., 3786.], device='cuda:0'), tensor([3786., 3786., 1482., 1482., 1482., 1482., 7932., 7932.,
7932., 7932.,
        7932., 7932.,  492.,  492.,  492.,  492.], device='cuda:0'), tensor([12003., 12003., 12003.,  9849., 12003., 12498., 12498.,
12498., 12003.,
        12498., 14301., 14301., 12498., 11883., 12498., 12003.],
       device='cuda:0'), tensor([12003., 12003., 11571., 12003.,  9849., 14301., 14301., 14301., 12498.,
        12498., 12498., 46245., 46245., 46245., 46245., 46245.],
       device='cuda:0'), tensor([46245., 46245., 46245., 46245., 46245., 46245., 32520., 46245., 46245.,
        32520., 32520., 32520., 32520., 32520., 32520., 32520.],
       device='cuda:0'), tensor([32520., 46245., 32520., 32520., 32520.], device='cuda:0')]

In [10]:
sum = [tensor([1.9574e+07, 2.0267e+07, 1.9411e+07, 1.2925e+08, 1.2970e+08, 1.2852e+08,
        1.3012e+08, 1.3009e+08, 1.2714e+08, 1.2911e+08, 1.6706e+07, 1.6516e+07,
        1.6535e+07, 1.6470e+07, 1.6679e+07, 1.8653e+07], device='cuda:0'), tensor([18860952., 19184276., 18698860., 46599400.,
46643224., 25550148.,
        25781914., 25773074., 25954396., 25934088., 23079176., 23168144.,
        23616194., 18726294., 18828190., 18932680.], device='cuda:0'), tensor([18338384., 18630568., 56830200., 57324084.,
56037904., 40440044.,
        41251344., 41957784., 40375184., 40817132., 40863160., 46335304.,
        46845856., 48002852., 47084548., 46288180.], device='cuda:0'), tensor([47507872., 13877214., 13718280., 13645110.,
72718256., 71402224.,
        73005824., 71911344., 72669592., 72971872., 73501904., 72753488.,
        73563872., 72977200., 72264112., 72596272.], device='cuda:0'), tensor([7.2655e+07, 7.2911e+07, 3.5548e+07, 3.3726e+07,
3.5149e+07, 3.5135e+07,
        1.3941e+08, 1.3803e+08, 1.3984e+08, 1.3990e+08, 1.3896e+08, 1.3996e+08,
        9.2918e+06, 9.1822e+06, 8.9530e+06, 9.1907e+06], device='cuda:0'), tensor([2.1768e+08, 2.1951e+08, 2.2147e+08, 2.1355e+08,
2.1998e+08, 2.2598e+08,
        2.2508e+08, 2.2609e+08, 2.2547e+08, 2.2774e+08, 2.7718e+08, 2.7623e+08,
        2.2414e+08, 1.9259e+08, 2.2424e+08, 2.2321e+08], device='cuda:0'), tensor([2.2466e+08, 2.2182e+08, 2.5323e+08, 2.2446e+08,
2.1509e+08, 2.7583e+08,
        2.7387e+08, 2.7341e+08, 2.2783e+08, 2.2791e+08, 2.3097e+08, 9.3252e+08,
        9.2540e+08, 9.2587e+08, 9.1819e+08, 9.2390e+08], device='cuda:0'), tensor([9.1233e+08, 9.1744e+08, 9.4141e+08, 9.3672e+08,
9.1867e+08, 9.2557e+08,
        5.2621e+08, 9.2406e+08, 9.4488e+08, 5.2398e+08, 5.2425e+08, 5.2029e+08,
        5.2010e+08, 5.2211e+08, 5.1931e+08, 5.2302e+08], device='cuda:0'), tensor([5.1897e+08, 9.1553e+08, 5.1680e+08, 5.3144e+08,
5.2899e+08],
       device='cuda:0')]

In [11]:
sum

[tensor([1.9574e+07, 2.0267e+07, 1.9411e+07, 1.2925e+08, 1.2970e+08, 1.2852e+08,
         1.3012e+08, 1.3009e+08, 1.2714e+08, 1.2911e+08, 1.6706e+07, 1.6516e+07,
         1.6535e+07, 1.6470e+07, 1.6679e+07, 1.8653e+07], device='cuda:0'),
 tensor([18860952., 19184276., 18698860., 46599400., 46643224., 25550148.,
         25781914., 25773074., 25954396., 25934088., 23079176., 23168144.,
         23616194., 18726294., 18828190., 18932680.], device='cuda:0'),
 tensor([18338384., 18630568., 56830200., 57324084., 56037904., 40440044.,
         41251344., 41957784., 40375184., 40817132., 40863160., 46335304.,
         46845856., 48002852., 47084548., 46288180.], device='cuda:0'),
 tensor([47507872., 13877214., 13718280., 13645110., 72718256., 71402224.,
         73005824., 71911344., 72669592., 72971872., 73501904., 72753488.,
         73563872., 72977200., 72264112., 72596272.], device='cuda:0'),
 tensor([7.2655e+07, 7.2911e+07, 3.5548e+07, 3.3726e+07, 3.5149e+07, 3.5135e+07,
         1.3941

In [12]:
sum_squared_error = torch.cat([values.flatten() for values in sum])
total = torch.cat([values.flatten() for values in total])

In [13]:
total

tensor([  873.,   873.,   873.,  6498.,  6498.,  6498.,  6498.,  6498.,  6498.,
         6498.,   333.,   333.,   333.,   333.,   333.,   762.,   762.,   762.,
          762.,  1986.,  1986.,  1296.,  1296.,  1296.,  1296.,  1296.,  1248.,
         1248.,  1248.,  1074.,  1074.,  1074.,  1074.,  1074.,  2481.,  2481.,
         2481.,  2586.,  2586.,  2586.,  2586.,  2586.,  2586.,  1959.,  1959.,
         1959.,  1959.,  1959.,  1959.,   741.,   741.,   741.,  3786.,  3786.,
         3786.,  3786.,  3786.,  3786.,  3786.,  3786.,  3786.,  3786.,  3786.,
         3786.,  3786.,  3786.,  1482.,  1482.,  1482.,  1482.,  7932.,  7932.,
         7932.,  7932.,  7932.,  7932.,   492.,   492.,   492.,   492., 12003.,
        12003., 12003.,  9849., 12003., 12498., 12498., 12498., 12003., 12498.,
        14301., 14301., 12498., 11883., 12498., 12003., 12003., 12003., 11571.,
        12003.,  9849., 14301., 14301., 14301., 12498., 12498., 12498., 46245.,
        46245., 46245., 46245., 46245., 

In [14]:
sum_squared_error

tensor([1.9574e+07, 2.0267e+07, 1.9411e+07, 1.2925e+08, 1.2970e+08, 1.2852e+08,
        1.3012e+08, 1.3009e+08, 1.2714e+08, 1.2911e+08, 1.6706e+07, 1.6516e+07,
        1.6535e+07, 1.6470e+07, 1.6679e+07, 1.8653e+07, 1.8861e+07, 1.9184e+07,
        1.8699e+07, 4.6599e+07, 4.6643e+07, 2.5550e+07, 2.5782e+07, 2.5773e+07,
        2.5954e+07, 2.5934e+07, 2.3079e+07, 2.3168e+07, 2.3616e+07, 1.8726e+07,
        1.8828e+07, 1.8933e+07, 1.8338e+07, 1.8631e+07, 5.6830e+07, 5.7324e+07,
        5.6038e+07, 4.0440e+07, 4.1251e+07, 4.1958e+07, 4.0375e+07, 4.0817e+07,
        4.0863e+07, 4.6335e+07, 4.6846e+07, 4.8003e+07, 4.7085e+07, 4.6288e+07,
        4.7508e+07, 1.3877e+07, 1.3718e+07, 1.3645e+07, 7.2718e+07, 7.1402e+07,
        7.3006e+07, 7.1911e+07, 7.2670e+07, 7.2972e+07, 7.3502e+07, 7.2753e+07,
        7.3564e+07, 7.2977e+07, 7.2264e+07, 7.2596e+07, 7.2655e+07, 7.2911e+07,
        3.5548e+07, 3.3726e+07, 3.5149e+07, 3.5135e+07, 1.3941e+08, 1.3803e+08,
        1.3984e+08, 1.3990e+08, 1.3896e+

In [16]:
base = 10
range = tensor(255)
psnr_base_e = 2 * torch.log(range) - torch.log(sum_squared_error / total)
psnr_vals = psnr_base_e * (10 / torch.log(tensor(base)))

In [17]:
psnr_vals

tensor([4.6241, 4.4730, 4.6605, 5.1443, 5.1292, 5.1689, 5.1152, 5.1162, 5.2158,
        5.1490, 1.1265, 1.1762, 1.1712, 1.1883, 1.1335, 4.2429, 4.1947, 4.1209,
        4.2322, 4.4268, 4.4227, 5.1829, 5.1437, 5.1452, 5.1147, 5.1181, 5.4607,
        5.4440, 5.3609, 5.7163, 5.6928, 5.6687, 5.8072, 5.7386, 4.5313, 4.4937,
        4.5923, 6.1890, 6.1027, 6.0290, 6.1959, 6.1487, 6.1438, 4.3920, 4.3444,
        4.2385, 4.3224, 4.3964, 4.2835, 5.4060, 5.4560, 5.4792, 5.2962, 5.3755,
        5.2790, 5.3446, 5.2991, 5.2811, 5.2496, 5.2941, 5.2460, 5.2807, 5.3234,
        5.3035, 5.3000, 5.2847, 4.3311, 4.5596, 4.3802, 4.3819, 5.6817, 5.7249,
        5.6683, 5.6665, 5.6957, 5.6646, 5.3695, 5.4210, 5.5308, 5.4170, 5.5455,
        5.5092, 5.4706, 4.7697, 5.4999, 5.5585, 5.5758, 5.5564, 5.3928, 5.5248,
        5.2568, 5.2718, 5.5940, 6.0337, 5.5921, 5.4366, 5.4084, 5.4637, 4.7294,
        5.4123, 4.7385, 5.2781, 5.3090, 5.3163, 5.5231, 5.5216, 5.4637, 5.0849,
        5.1182, 5.1159, 5.1521, 5.1252, 

In [18]:
torch.mean(psnr_vals)

tensor(5.1309, device='cuda:0')